### ISSUE TITLE
Error while Using

### ISSUE THREAD

**Issue by Siva2webdev** [ThatNotEasy/Widevine-KSKEY#11]
INFO     | Getting license keys for service: prime
2024-09-05 08:10:42 | INFO     | PSSH: CAESEOQvV++Zw0Y7pa3oK8OVFFQaBmFtYXpvbiI1Y2lkOm53d0VCamVaUUt1WnNqZ3VvTEx2Ync9PSw1QzlYNzVuRFJqdWxyZWdydzVVVVZBPT0qAlNEMgA=
2024-09-05 08:10:42 | INFO     | License URL: https://atv-ps-eu.amazon.co.uk/cdp/catalog/GetPlaybackResources?deviceID=8e90567f-5a04-4bff-9477-144a4f689d1f&deviceTypeID=AOAGZA014O5RE&gascEnabled=false&marketplaceID=A1F83G8C2ARO7P&uxLocale=en_GB&firmware=1&playerType=xp&operatingSystemName=Windows&operatingSystemVersion=10.0&deviceApplicationName=Chrome&asin=amzn1.dv.gti.34abea88-67e0-3261-7599-645cb107e723&consumptionType=Streaming&desiredResources=Widevine2License&resourceUsage=ImmediateConsumption&videoMaterialType=Feature&clientId=f22dbddb-ef2c-48c5-8876-bed0d47594fd&userWatchSessionId=8ee9a445-e4c1-4959-b1ea-d48d1c6b7e36&displayWidth=1920&displayHeight=1080&supportsVariableAspectRatio=true&supportsEmbeddedTimedTextForVod=false&deviceProtocolOverride=Https&vodStreamSupportOverride=Auxiliary&deviceStreamingTechnologyOverride=DASH&deviceDrmOverride=CENC&deviceAdInsertionTypeOverride=SSAI&deviceHdrFormatsOverride=None&deviceVideoCodecOverride=H264&deviceVideoQualityOverride=HD&deviceBitrateAdaptationsOverride=CVBR%2CCBR&supportsEmbeddedTrickplayForVod=false&playerAttributes=%7B%22middlewareName%22%3A%22Chrome%22%2C%22middlewareVersion%22%3A%22128.0.0.0%22%2C%22nativeApplicationName%22%3A%22Chrome%22%2C%22nativeApplicationVersion%22%3A%22128.0.0.0%22%2C%22supportedAudioCodecs%22%3A%22AAC%22%2C%22frameRate%22%3A%22HFR%22%2C%22H264.codecLevel%22%3A%224.2%22%2C%22H265.codecLevel%22%3A%220.0%22%2C%22AV1.codecLevel%22%3A%220.0%22%7D
{"error":{"errorCode":"PRS.InvalidRequest","message":"Cannot complete request.","type":"PRSInvalidRequestException"}}

Traceback (most recent call last):
  File "C:\Users\91918\Downloads\Widevine-KSKEY-2.3 (1)\main.py", line 87, in <module>
    main()
  File "C:\Users\91918\Downloads\Widevine-KSKEY-2.3 (1)\main.py", line 57, in main
    keys = get_license_keys(pssh, args.license_url, args.service, args.content_id, proxy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91918\Downloads\Widevine-KSKEY-2.3 (1)\modules\license_retrieval.py", line 91, in get_license_keys
    license_b64 = response.json()["widevine2License"]["license"]
                  ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'widevine2License'
![image](https://github.com/user-attachments/assets/3fcd750e-3b60-4f5f-a4fa-8f3952b2a346)

getting this error while using

**Comment by Ap0dexMe0** [comment]
change user-agent into linux
