### ISSUE TITLE
netflix service error 502

### ISSUE THREAD

**Issue by ElJoker63** [ThatNotEasy/Widevine-KSKEY#12]
```2024-09-08 02:47:45 | INFO     | You must provide both -d (downloads) and -m (MPD URL) to trigger the download.
========================================================================================================================{"BUILD_IDENTIFIER":"vb396e4f2","isProdVersion":true}
502
Traceback (most recent call last):
  File "C:\Users\User\Desktop\BACKUP\Widevine-KSKEY\main.py", line 156, in <module>
    main()
  File "C:\Users\User\Desktop\BACKUP\Widevine-KSKEY\main.py", line 38, in main
    handle_netflix(args)
  File "C:\Users\User\Desktop\BACKUP\Widevine-KSKEY\main.py", line 46, in handle_netflix
    asyncio.run(download_netflix(args.content_id, 'output'))
  File "C:\Program Files\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\User\Desktop\BACKUP\Widevine-KSKEY\services\netflix.py", line 1033, in download_netflix
    viewables = await loop.run_in_executor(None, client.get_viewables, content_id)
  File "C:\Program Files\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\User\Desktop\BACKUP\Widevine-KSKEY\services\netflix.py", line 177, in get_viewables
    metadata = self.get_metadata(any_id)
  File "C:\Users\User\Desktop\BACKUP\Widevine-KSKEY\services\netflix.py", line 147, in get_metadata
    raise NetflixStatusError(f"Netflix did not return 200 ({r.status_code})")
modules.errors.NetflixStatusError: Netflix did not return 200 (502)```

**Comment by Ap0dexMe0** [comment]
new construct.
