### ISSUE TITLE
CDM

### ISSUE THREAD

**Issue by whip28** [ThatNotEasy/Widevine-KSKEY#14]
Hi
I can't find where to put the CDM and how to make this script work.

**Comment by Ap0dexMe0** [comment]
create a device folder and paste cdm there.

**Comment by whip28** [comment]
Thank you

What information should I write to obtain the Videotron Helix keys?


python main.py --license-url [https://mds.vl.comcast.net/license] --m [https://vl-mw-cdnec002.ipvod-tve.cdnsrv.videotron.ca/ipvod13/ae7a763a-1786-461b-9af5-810a8c503a58/1726750250/M/HD/manifest.mpd] --pssh [AAAAfnBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAF4SJDc5MWJkMjQzLWQ0ODItNWU0Ni05Njk1LTE5NmVmZGI4MDljNyI2dmlkZW90cm9uLmNvbUFBQUEwMDAwMDA1OTc3MDMwMTAxLUFBQUEwMDAwMDA1OTc3MDMwMTAy] --kid [791bd243d4825e469695196efdb809c7] --service videotron



Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\construct\core.py", line 2696, in _parse
    return self.subcon._parse(stream, context, path)
  File "C:\Python39\lib\site-packages\construct\core.py", line 1881, in _parse
    raise ConstError("expected %r but parsed %r" % (self.value, obj))
construct.core.ConstError: expected 2 but parsed 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ \Downloads\Widevine-KSKEY-main (1)\main.py", line 209, in <module>
    main()
  File "C:\Users\ \Downloads\Widevine-KSKEY-main (1)\main.py", line 108, in main
    handle_other_services(args, headers)
  File "C:\Users\ \Downloads\Widevine-KSKEY-main (1)\main.py", line 117, in handle_other_services
    keys = get_license_keys(pssh, args.license_url, args.service, args.content_id or args.manifest_url, proxy)
  File "C:\Users\ \Downloads\Widevine-KSKEY-main (1)\modules\license_retrieval.py", line 54, in get_license_keys
    device = load_first_wvd_file()
  File "C:\Users\ \Downloads\Widevine-KSKEY-main (1)\modules\license_retrieval.py", line 26, in load_first_wvd_file
    return Device.load(wvd_files[0])
  File "C:\Python39\lib\site-packages\pywidevine\device.py", line 164, in load
    return cls(**cls.supported_structure.parse_stream(f))
  File "C:\Python39\lib\site-packages\construct\core.py", line 186, in parse_stream
    return self._parse(stream, context, "parsing")
  File "C:\Python39\lib\site-packages\construct\core.py", line 859, in _parse
    subobj = sc._parse(stream, context, path)
  File "C:\Python39\lib\site-packages\construct\core.py", line 2700, in _parse
    raise e.__class__("%s\n    %s" % (e, path))
construct.core.ConstError: expected 2 but parsed 1
    parsing -> version

C:\Users\ \Downloads\Widevine-KSKEY-main (1)>

**Comment by whip28** [comment]
What is the problem for this error?

python main.py -u https://mds.vl.comcast.net/license -m https://vl-mw-cdnec003.ipvod-tve.cdnsrv.videotron.ca/ipvod13/ae7a763a-1786-461b-9af5-810a8c503a58/1726750250/M/HD/manifest.mpd -s videotron

Traceback (most recent call last):
File "C:\Python39\lib\site-packages\construct\core.py", line 2696, in _parse
return self.subcon._parse(stream, context, path)
File "C:\Python39\lib\site-packages\construct\core.py", line 1881, in _parse
raise ConstError("expected %r but parsed %r" % (self.value, obj))
construct.core.ConstError: expected 2 but parsed 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\ \Downloads\Widevine-KSKEY-main\main.py", line 201, in
main()
File "C:\Users\ \Downloads\Widevine-KSKEY-main\main.py", line 100, in main
handle_other_services(args, headers)
File "C:\Users\ \Downloads\Widevine-KSKEY-main\main.py", line 109, in handle_other_services
keys = get_license_keys(pssh, args.license_url, args.service, args.content_id or args.manifest_url, proxy)
File "C:\Users\ \Downloads\Widevine-KSKEY-main\modules\license_retrieval.py", line 54, in get_license_keys
device = load_first_wvd_file()
File "C:\Users\ \Downloads\Widevine-KSKEY-main\modules\license_retrieval.py", line 26, in load_first_wvd_file
return Device.load(wvd_files[0])
File "C:\Python39\lib\site-packages\pywidevine\device.py", line 164, in load
return cls(**cls.supported_structure.parse_stream(f))
File "C:\Python39\lib\site-packages\construct\core.py", line 186, in parse_stream
return self._parse(stream, context, "parsing")
File "C:\Python39\lib\site-packages\construct\core.py", line 859, in _parse
subobj = sc._parse(stream, context, path)
File "C:\Python39\lib\site-packages\construct\core.py", line 2700, in _parse
raise e.class("%s\n %s" % (e, path))
construct.core.ConstError: expected 2 but parsed 1
parsing -> version

C:\Users\ \Downloads\Widevine-KSKEY-main>
