### ISSUE TITLE
Unable to retrieve key for skyshowtime

### ISSUE THREAD

**Issue by nonab** [ThatNotEasy/Widevine-KSKEY#21]
Command i tried 

```python main.py -m "https://015938c764de4649a6cebffb7b61602c.mediatailor.eu-central-1.amazonaws.com/v1/dash/d89ec62454be0bf5ac10fca7674c77176f0b9ce5/sst-dash-vod-2s-generic/pub/global/IHr/0Hb/GMO_00000000222446_02/SST_1709718635010_5fe7_01/mpeg_cenc_2sec/master_manifest_default_r12.mpd?c3.ri=13628863223503935955&audio=all&subtitle=all&forcedNarrative=true&trickplay=true&audioCodec=mp4a.40.2%2Cmp4a.40.5&aws.sessionId=183b066e-f5da-4b63-9b08-bad3e6d983bf" -s skyshowtime  -u "https://ovp.skyshowtime.com/drm/widevine/acquirelicense?bt=13-Zt2O38AYo462SUOETjol6sU7QG4xjoAq-0uj6mHjWzUeYxJiXyVawMsDQtfcQb2DNBmqX3AQTKfGKUl8okaj3b5lXlhd13vaE_Kcxn_t0Scbr8m2bONED0fgWRqWCz3ibYOBX7JXPgCrE2qw7xUDAD3Ovo393QEkbOP8LmSGOF95O-gSIfAi402Y_nMfRToLfJ8Nw8j6os91NttcEsMjMoWlIe2y62aqPrlpLxo1RFMo8C0nK13kAAcuoBL4rEdT_2yuMwQRqOjwF55GkfxFnPp1-09ghWWTEZd5yimqyF01zcOQ6eb2TJou0VWCFFXlDfOGFNIO0ZIhweO2nPjJu1J6qoEweAHQ_ZiR7PtHBMpOZaLc82s455dEp-ZZD1CPRgyS_eCgnIZjhe8zgkoNen557vGt8bG4Gvw-FH4LGTjQ"```

what i get is 

```
 _       ___     __          _                  __ _______ __ __ ________  __
| |     / (_)___/ /__ _   __(_)___  ___        / //_/ ___// //_// ____/\ \/ /
| | /| / / / __  / _ \ | / / / __ \/ _ \______/ ,<  \__ \/ ,<  / __/    \  /
| |/ |/ / / /_/ /  __/ |/ / / / / /  __/_____/ /| |___/ / /| |/ /___    / /
|__/|__/_/\__,_/\___/|___/_/_/ /_/\___/     /_/ |_/____/_/ |_/_____/   /_/

Running
Disclaimer: You must provide both '-d --downloads & -m --manifest-url' to trigger the download. (HLS ONLY)
========================================================================================================================

2024-11-08 21:33:20 | INFO     | MANIFEST: https://015938c764de4649a6cebffb7b61602c.mediatailor.eu-central-1.amazonaws.com/v1/dash/d89ec62454be0bf5ac10fca7674c77176f0b9ce5/sst-dash-vod-2s-generic/pub/global/IHr/0Hb/GMO_00000000222446_02/SST_1709718635010_5fe7_01/mpeg_cenc_2sec/master_manifest_default_r12.mpd?c3.ri=13628863223503935955&audio=all&subtitle=all&forcedNarrative=true&trickplay=true&audioCodec=mp4a.40.2%2Cmp4a.40.5&aws.sessionId=183b066e-f5da-4b63-9b08-bad3e6d983bf
=============================================================================================================
2024-11-08 21:33:21 | INFO     | KID: 0000c854-cbfd-6dea-30fe-f35c21939ef9
========================================================================================================================
2024-11-08 21:33:21 | INFO     | SERVICE: skyshowtime
========================================================================================================================
2024-11-08 21:33:21 | INFO     | PSSH: AAAAOHBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAABgSEAAAyFTL/W3qMP7zXCGTnvlI49yVmwY=
========================================================================================================================
2024-11-08 21:33:21 | INFO     | LICENSE: https://ovp.skyshowtime.com/drm/widevine/acquirelicense?bt=13-Zt2O38AYo462SUOETjol6sU7QG4xjoAq-0uj6mHjWzUeYxJiXyVawMsDQtfcQb2DNBmqX3AQTKfGKUl8okaj3b5lXlhd13vaE_Kcxn_t0Scbr8m2bONED0fgWRqWCz3ibYOBX7JXPgCrE2qw7xUDAD3Ovo393QEkbOP8LmSGOF95O-gSIfAi402Y_nMfRToLfJ8Nw8j6os91NttcEsMjMoWlIe2y62aqPrlpLxo1RFMo8C0nK13kAAcuoBL4rEdT_2yuMwQRqOjwF55GkfxFnPp1-09ghWWTEZd5yimqyF01zcOQ6eb2TJou0VWCFFXlDfOGFNIO0ZIhweO2nPjJu1J6qoEweAHQ_ZiR7PtHBMpOZaLc82s455dEp-ZZD1CPRgyS_eCgnIZjhe8zgkoNen557vGt8bG4Gvw-FH4LGTjQ
========================================================================================================================
Traceback (most recent call last):
  File "G:\Temp\python\Widevine-KSKEY\main.py", line 209, in <module>
    main()
  File "G:\Temp\python\Widevine-KSKEY\main.py", line 108, in main
    handle_other_services(args, headers)
  File "G:\Temp\python\Widevine-KSKEY\main.py", line 117, in handle_other_services
    keys = get_license_keys(pssh, args.license_url, args.service, args.content_id or args.manifest_url, proxy)
  File "G:\Temp\python\Widevine-KSKEY\modules\license_retrieval.py", line 122, in get_license_keys
    region = cookies['activeTerritory']
KeyError: 'activeTerritory'
```

I have tried to hardcode it but no luck.

```
2024-11-08 21:44:10 | INFO     | MANIFEST: https://015938c764de4649a6cebffb7b61602c.mediatailor.eu-central-1.amazonaws.com/v1/dash/d89ec62454be0bf5ac10fca7674c77176f0b9ce5/sst-dash-vod-2s-generic/pub/global/IHr/0Hb/GMO_00000000222446_02/SST_1709718635010_5fe7_01/mpeg_cenc_2sec/master_manifest_default_r12.mpd?c3.ri=13628863223503935955&audio=all&subtitle=all&forcedNarrative=true&trickplay=true&audioCodec=mp4a.40.2%2Cmp4a.40.5&aws.sessionId=183b066e-f5da-4b63-9b08-bad3e6d983bf
=============================================================================================================
2024-11-08 21:44:11 | INFO     | KID: 0000c854-cbfd-6dea-30fe-f35c21939ef9
========================================================================================================================
2024-11-08 21:44:11 | INFO     | SERVICE: skyshowtime
========================================================================================================================
2024-11-08 21:44:11 | INFO     | PSSH: AAAAOHBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAABgSEAAAyFTL/W3qMP7zXCGTnvlI49yVmwY=
========================================================================================================================
2024-11-08 21:44:11 | INFO     | LICENSE: https://ovp.skyshowtime.com/drm/widevine/acquirelicense?bt=13-GQJhwVReQPtwP9oynKiYCOsOZg3ndE41S9nUxqFmIL7pJxyJS6JugBWrUhfPqkw06nCnH2U1in9_BvEYyzgHsKumFvRgJcRaklMkyMyQ0ZYHLaEnnBE2NCI4FXm6DBRFSgYHI-EOg31vlJplRZ95DfbozO__30biOIBXockJEdm9qS0Qc44oNT8s3amQwa9cmGtz7lnXzYWqGyaLK7Wff3nMoS7kANoyx3oHI4NJkAUGBzFE-QEXTrCluaCxPeb4rJ73W8q0CwLKJaLli0dihUR8S4in4L6Tcgo9oIjuwKYqnlkIB3x9CwagHOslGG-MHjUxn4mwC1LwXWSzyGmA-GG-Ev6vFSStGcLqDKwf2IXoBbe0rBeF-J8MnBThB27KsgntJK6sGu_MxZDbQX9kJCDBVejcaVw6VL9nTr4E8tpu
========================================================================================================================
2024-11-08 21:44:11 | INFO     | Status: 400 Client Error: Bad Request for url: https://ovp.skyshowtime.com/auth/tokens
```

Looks like passing cookies is missing or something ?

i also tried exporting my skyshowtime cookies and loading them in the service and then a different error pops up

```
2024-11-08 21:46:08 | INFO     | Status: 404 Client Error: Not Found for url: https://ovp.skyshowtime.com/video/playouts/vod
```

**Comment by Ap0dexMe0** [comment]
can u do just like content watch url?
```bash
$ python main.py -m "<WATCH_URL>" -s "skyshowtime"
```
watch url example:
```bash
https://www.skyshowtime.com/watch/asset/tv/big-time-rush/0f0de973-955e-3f79-be5f-c7b9e63b335f
```

**Comment by nonab** [comment]
> can u do just like content watch url?
> 
> ```shell
> $ python main.py -m "<WATCH_URL>" -s "skyshowtime"
> ```
> 
> watch url example:
> 
> ```shell
> https://www.skyshowtime.com/watch/asset/tv/big-time-rush/0f0de973-955e-3f79-be5f-c7b9e63b335f
> ```

```
2024-11-10 10:52:59 | INFO     | MANIFEST: https://www.skyshowtime.com/watch/playback/vod/big-time-rush/1466f227-379b-3945-a17f-132aa02f475c
=============================================================================================================
2024-11-10 10:53:00 | WARNING  | Unsupported manifest URL type.
2024-11-10 10:53:00 | ERROR    | No PSSH data provided or extracted.
```

**Comment by Ap0dexMe0** [comment]
> > can u do just like content watch url?
> > ```shell
> > $ python main.py -m "<WATCH_URL>" -s "skyshowtime"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > watch url example:
> > ```shell
> > https://www.skyshowtime.com/watch/asset/tv/big-time-rush/0f0de973-955e-3f79-be5f-c7b9e63b335f
> > ```
> 
> ```
> 2024-11-10 10:52:59 | INFO     | MANIFEST: https://www.skyshowtime.com/watch/playback/vod/big-time-rush/1466f227-379b-3945-a17f-132aa02f475c
> =============================================================================================================
> 2024-11-10 10:53:00 | WARNING  | Unsupported manifest URL type.
> 2024-11-10 10:53:00 | ERROR    | No PSSH data provided or extracted.
> ```

please dm me on telegram [@SurpriseMTFK](https://telegram.me/SurpriseMTFK)
