### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by Khysnik** [ThatNotEasy/Widevine-KSKEY#3]
Hey, I was just wondering if this project requires a certain version of python, I had to go in and fix errors with the collections module, and now i'm getting a ton of errors from the ssl module. Here is the error

Traceback (most recent call last):
  File "C:\Users\Pangea\AppData\Local\Programs\Python\Python312\Lib\site-packages\hyper\tls.py", line 50, in wrap_socket
    ssl.match_hostname(ssl_sock.getpeercert(), server_hostname)
    ^^^^^^^^^^^^^^^^^^
AttributeError: module 'ssl' has no attribute 'match_hostname'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Pangea\Downloads\Widevine-KSKEY-main\main.py", line 140, in <module>
    main()
  File "C:\Users\Pangea\Downloads\Widevine-KSKEY-main\main.py", line 31, in main
    handle_netflix(args)
  File "C:\Users\Pangea\Downloads\Widevine-KSKEY-main\main.py", line 39, in handle_netflix
    asyncio.run(download_netflix(args.content_id, 'output'))
  File "C:\Users\Pangea\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Pangea\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pangea\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Pangea\Downloads\Widevine-KSKEY-main\services\netflix.py", line 986, in download_netflix
    client = NetflixClient(email=f"{EMAIL}",password=f"{PASSWORD}",device=get_current_directory())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pangea\Downloads\Widevine-KSKEY-main\services\netflix.py", line 109, in __init__
    self.msl: MSLClient = MSLClient(self)
                          ^^^^^^^^^^^^^^^
  File "C:\Users\Pangea\Downloads\Widevine-KSKEY-main\services\netflix.py", line 463, in __init__
    return self.session_keys.update(self.generate_handshake())
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pangea\Downloads\Widevine-KSKEY-main\services\netflix.py", line 505, in generate_handshake
    r = self.session.post(self.msl_url, json=request,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pangea\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pangea\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pangea\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pangea\AppData\Local\Programs\Python\Python312\Lib\site-packages\hyper\contrib.py", line 74, in send
    conn.request(
  File "C:\Users\Pangea\AppData\Local\Programs\Python\Python312\Lib\site-packages\hyper\common\connection.py", line 102, in request
    return self._conn.request(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pangea\AppData\Local\Programs\Python\Python312\Lib\site-packages\hyper\http11\connection.py", line 169, in request
    self.connect()
  File "C:\Users\Pangea\AppData\Local\Programs\Python\Python312\Lib\site-packages\hyper\http11\connection.py", line 124, in connect
    sock, proto = wrap_socket(sock, host, self.ssl_context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pangea\AppData\Local\Programs\Python\Python312\Lib\site-packages\hyper\tls.py", line 52, in wrap_socket
    ssl.verify_hostname(ssl_sock, server_hostname)  # pyopenssl
    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'ssl' has no attribute 'verify_hostname'

**Comment by Ap0dexMe0** [comment]
the netflix currently is not working anymore, i will update it.
