### ISSUE TITLE
Netflix login error

### ISSUE THREAD

**Issue by Khysnik** [ThatNotEasy/Widevine-KSKEY#6]
An error occurred: Email or password is incorrect.
Traceback (most recent call last):
  File "C:\Users\Pangea\Downloads\Widevine-KSKEY-main\main.py", line 145, in <module>
    main()
  File "C:\Users\Pangea\Downloads\Widevine-KSKEY-main\main.py", line 31, in main
    handle_netflix(args)
  File "C:\Users\Pangea\Downloads\Widevine-KSKEY-main\main.py", line 39, in handle_netflix
    asyncio.run(download_netflix(args.content_id, 'output'))
  File "C:\Users\Pangea\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Pangea\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pangea\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Pangea\Downloads\Widevine-KSKEY-main\services\netflix.py", line 1035, in download_netflix
    await viewables[0].download()
  File "C:\Users\Pangea\Downloads\Widevine-KSKEY-main\services\netflix.py", line 302, in download
    playlist = Parse(self.client.msl.load_playlist(self.vid), self.client)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pangea\Downloads\Widevine-KSKEY-main\services\netflix.py", line 765, in load_playlist
    raise LoginError(manifest.get("error", {}).get("display", error))
modules.errors.LoginError: Email or password is incorrect.

I double checked and the username/password in the config are correct. Any fix?

**Comment by Ap0dexMe0** [comment]
netflix not working rayt now for android cdm, need chrome cdm.

**Comment by Khysnik** [comment]
How would you get a chrome cdm? Can you get it from chrome browser, ChomeOS? I only know how to extract keys from android, lol 😅
