### ISSUE TITLE
Netflix- Email or password is incorrect

### ISSUE THREAD

**Issue by ApeDevOne** [ThatNotEasy/Widevine-KSKEY#8]
An error occurred: Email or password is incorrect.
Traceback (most recent call last):
  File "K:\Ripping\Widevine-KSKEY\main.py", line 151, in <module>
    main()
  File "K:\Ripping\Widevine-KSKEY\main.py", line 30, in main
    handle_netflix(args)
  File "K:\Ripping\Widevine-KSKEY\main.py", line 38, in handle_netflix
    asyncio.run(download_netflix(args.content_id, 'output'))
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "K:\Ripping\Widevine-KSKEY\services\netflix.py", line 1035, in download_netflix
    await viewables[0].download()
  File "K:\Ripping\Widevine-KSKEY\services\netflix.py", line 302, in download
    playlist = Parse(self.client.msl.load_playlist(self.vid), self.client)
  File "K:\Ripping\Widevine-KSKEY\services\netflix.py", line 765, in load_playlist
    raise LoginError(manifest.get("error", {}).get("display", error))
modules.errors.LoginError: Email or password is incorrect.

**Comment by ApeDevOne** [comment]
Is MSL still broken?

**Comment by Ap0dexMe0** [comment]
yes, still construct.
